apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
  namespace: application
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: bobby84/fastapi:3aa91ef99d363604b941bcc01e1daa9a9e96d822
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-fastapi-configmap
