name: Scan Fast API app on pull request pipeline
run-name: Scan Fast API app on pull request pipeline

on:
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  gitleaks-scan:
    name: GitLeaks scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  editorconfig:
    name: EditorConfig Checker
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  python-pylint:
    name: Executes pylint
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          path: "./*.py"
          fail: true
          pr-message: true

  python-black:
    name: Python Black
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - uses: actions/checkout@v3
      - name: Python Black
        uses: cytopia/docker-black@0.8
        with:
          path: 'app/'

  markdownlint-cli:
    name: Markdownlint CLI
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli

      - name: Run Markdownlint
        run: markdownlint **/*.md

  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: LOG_LEVEL=${{ vars.LOG_LEVEL }} python -m pytest
